### ISSUE TITLE
aise ImportError("libcaer might not be in the LD_LIBRARY_PATH "

### ISSUE THREAD

**Issue by yalanazi8022** [duguyue100/pyaer#14]
Hi,

I am trying to run davis240_test.py on my Mac laptop but getting this error: 

"ImportError: libcaer might not be in the LD_LIBRARY_PATH or your numpy might not be the required version.Try to load _libcaer_wrap.so from the package directory, this will provide more information."

Can you please advise me ?

Regards,
Y

**Comment by duguyue100** [comment]
Hi, can you provide some brief info of your installation and environment?

OS:
Python version:
Numpy version:
Have you installed `libcaer`?:
Which version of `pyaer` you installed?:

Yuhuang.

**Comment by yalanazi8022** [comment]
Hi,

Thank you for your answer. These the answers:
- OS: MacOS Mojava 
- Python version: 3.7.3
- Numpy version 1.16.4 
- Yes, I have installed libcear
- Payer version: 0.1.6

**Comment by duguyue100** [comment]
Hi, @yalanazi8022 ,

I reproduced your environment and now I can confirm that the package is fine because I could run some simple demos with Python 3.7.3+pyaer 0.1.6+numpy 1.16.4+MacOS Mojava.

Just to be correct, did you install the libcaer through `homebrew` or the following command:
```
bash <(curl -s https://raw.githubusercontent.com/duguyue100/pyaer/master/install-libcaer.sh)
```

The latter command will install `libcaer` at the correct version that is built against pyaer 0.1.6.

Usually, this error suggests that pyaer couldn't find the correct `libcaer` in the system search path.
It should be fine if `libcaer` is installed at `/usr/local`.

One last thing to try is importing the compiled binary directly, you can find pyaer installation. Find this file `_libcaer_wrap.cpython-37m-darwin.so`, open a terminal at the folder that has this file, run `python`, and `import _libcaer_wrap`. It should give you more information.

Regards,
Yuhuang.

**Comment by shirleyatgithub** [comment]
I execute the command 
bash <(curl -s https://raw.githubusercontent.com/duguyue100/pyaer/master/install-libcaer.sh)
but the libcaer is written into /tmp/libcaer/ rather that /usr/local/

**Comment by duguyue100** [comment]
@shirleyatgithub Yes, that is intended when you install library. It will finally installed into /usr/local
