### ISSUE TITLE
Installing pyaer on WIndows 10

### ISSUE THREAD

**Issue by AnxheloKamberi** [duguyue100/pyaer#18]
Hello, is it possible to install pyaer library on Windows 10? 

Thank for your time.

**Comment by duguyue100** [comment]
Yes, it's possible. I stopped supporting the Windows build because the Appveyor supports somehow breaks and I couldn't fix it.

The trick is to use MINGW and you need to build from source. The installation for `libcaer` is here: https://github.com/duguyue100/pyaer/blob/master/install-libcaer.sh#L57

And the CI/CD config I was using is here: https://github.com/duguyue100/pyaer/blob/master/res/appveyor.yml

By the way, I don't think it works with the Linux subsystem in Windows. You want to build `.lib` libraries for your Python.

Let me know if there is additional problems, I have to say it's a bit annoying to get it right on Windows.
